name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 6 * * *" #runs at 06:00 UTC everyday

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies 🔧
        run: |
          pip3 install -r requirements.txt
          pip3 install Pillow

      - name: Download days history
        uses: dawidd6/action-download-artifact@v2
        continue-on-error: true
        with:
          workflow: main.yml
          workflow_conclusion: success
          name: days-history

      - name: Build
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 30
          max_attempts: 5
          command: python3 main.py

      - name: Upload days history
        uses: actions/upload-artifact@v2
        with:
          name: days-history
          path: days_history.dat

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: generated
          CLEAN: true
